name: Update TD Github copy

on:
  workflow_dispatch:
  schedule:
     - cron:  '* * * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.repository == 'DeveloperTools/dbt-teradata'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Update TD GitHub copy
        shell: bash
        run: |
          set -v
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
          # we add remote, ignore error if it already exists
          git remote add very-origin https://$REMOTE_GH_TOKEN@github.com/Teradata/dbt-teradata || true
          git pull very-origin main
          git push origin main
        env:
          REMOTE_GH_TOKEN: ${{ secrets.REMOTE_GH_TOKEN }}
